CREATE DATABASE TokoKosmetik;

CREATE TABLE Customer
(
    IDCust CHAR(5) PRIMARY KEY NOT NULL,
    Nama VARCHAR(50) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    Notelp VARCHAR(15) NOT NULL,
    Alamat VARCHAR(50) NOT NULL
);

CREATE TABLE Transaksi(
    IDTransaksi CHAR(5) PRIMARY KEY NOT NULL,
    Tanggal TIMESTAMP NOT NULL,
    HargaTotal NUMERIC(8,2) NOT NULL
);

CREATE TABLE Detail_Transaksi(
    IDDet_Tran CHAR(5) PRIMARY KEY NOT NULL,
    Jumlah INTEGER NOT NULL;
    HargaTOTAl NUMERIC(8,2) NOT NULL
);

CREATE TABLE Produk(
    IDProduk CHAR(5) PRIMARY KEY NOT NULL,
    Nama VARCHAR(60) NOT NULL,
    EXPDate TIMESTAMP NOT NULL,
    Harga NUMERIC(8,2) NOT NULL,
    Stok INTEGER NOT NULL
);

CREATE TABLE Brand(
    IDBrand CHAR(5) PRIMARY KEY NOT NULL,
    Nama VARCHAR(30) NOT NULL
);
